import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="text-center pt-32 px-5">
      <h1 className="text-4xl font-bold mb-5 md:text-5xl">
        Welcome to my blog
      </h1>
      <p className="max-w-[750px] mx-auto leading-8">
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolore omnis iste pariatur earum perspiciatis maxime similique quis consectetur fuga officia unde numquam laudantium, ad quidem, odio veniam nobis sit praesentium.
      </p>
    </main>
  )
}
